<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Profesional extends \Entity\Profesional implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdprofesional()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idprofesional"];
        }
        $this->__load();
        return parent::getIdprofesional();
    }

    public function setActividad($actividad)
    {
        $this->__load();
        return parent::setActividad($actividad);
    }

    public function getActividad()
    {
        $this->__load();
        return parent::getActividad();
    }

    public function setNccc($nccc)
    {
        $this->__load();
        return parent::setNccc($nccc);
    }

    public function getNccc()
    {
        $this->__load();
        return parent::getNccc();
    }

    public function setLogin(\Entity\Users $login = NULL)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setIddelegacion(\Entity\Delegaciones $iddelegacion = NULL)
    {
        $this->__load();
        return parent::setIddelegacion($iddelegacion);
    }

    public function getIddelegacion()
    {
        $this->__load();
        return parent::getIddelegacion();
    }

    public function setIdpersonas(\Entity\Personas $idpersonas = NULL)
    {
        $this->__load();
        return parent::setIdpersonas($idpersonas);
    }

    public function getIdpersonas()
    {
        $this->__load();
        return parent::getIdpersonas();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idprofesional', 'actividad', 'nccc', 'login', 'iddelegacion', 'idpersonas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}