<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ingresos extends \Entity\Ingresos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdingresos()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idingresos"];
        }
        $this->__load();
        return parent::getIdingresos();
    }

   

    public function setIdcaja(\Entity\Cajas $idcaja = NULL)
    {
        $this->__load();
        return parent::setIdcaja($idcaja);
    }

    public function getIdcaja()
    {
        $this->__load();
        return parent::getIdcaja();
    }

    public function setIdtipoingreso(\Entity\TiposIngreso $idtipoingreso = NULL)
    {
        $this->__load();
        return parent::setIdtipoingreso($idtipoingreso);
    }

    public function getIdtipoingreso()
    {
        $this->__load();
        return parent::getIdtipoingreso();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idingresos', 'idcaja', 'idtipoingreso');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}